services:
  - type: web
    name: mailzon
    env: node
    branch: dev
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    healthCheckPath: /health
